# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ModelManagementToolsDockWidget
                                 A QGIS plugin
 A plugin for manage models
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-13
        git sha              : $Format:%H$
        copyright            : (C) 2019 by David Hernandez Lopez, Universidad de Castilla-La Mancha
        email                : david.hernandez@uclm.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# dhl
import sys,os
from osgeo import osr
from decimal import Decimal
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QFileInfo, QDir, QObject
from PyQt5.QtWidgets import QMessageBox,QFileDialog,QTabWidget,QInputDialog,QLineEdit
from PyQt5.QtWidgets import QDockWidget
from qgis.core import QgsApplication, QgsDataSourceUri
# pluginsPath = QFileInfo(QgsApplication.qgisUserDatabaseFilePath()).path()
# pluginPath = os.path.dirname(os.path.realpath(__file__))
# pluginPath = os.path.join(pluginsPath, pluginPath)
# libCppPath = os.path.join(pluginPath, 'libCpp')
# existsPluginPath = QDir(libCppPath).exists()
# sys.path.append(pluginPath)
# sys.path.append(libCppPath)
# os.environ["PATH"] += os.pathsep + libCppPath
# from libCpp.libPyModelManagementTools import IPyModelManagementToolsProject
from .multipleFileSelectorDialog.multiple_file_selector_dialog import * #panel nueva camara
# import MMTDefinitions
from . import MMTDefinitions
#  dhl

import os

from math import floor
import re

from PyQt5 import QtGui, QtWidgets, uic
from PyQt5.QtCore import pyqtSignal

from qgis import utils

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'model_management_tools_dockwidget_base.ui'))

class ModelManagementToolsDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self,
                 iface,
                 pluginPath,
                 libCppPath,
                 currentPluginName,
                 settings,
                 iPyProject,
                 parent=None):
        """Constructor."""
        super(ModelManagementToolsDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setWindowTitle(MMTDefinitions.CONST_PROGRAM_NAME)
        self.iface = iface
        self.path_plugin = pluginPath
        self.path_libCpp = libCppPath
        self.current_plugin_name = currentPluginName
        self.settings = settings
        self.iPyProject = iPyProject
        self.isModelManagementPlugin = False
        self.plugin_name = None
        if self.current_plugin_name == MMTDefinitions.CONST_SETTINGS_PLUGIN_NAME:
            self.isModelManagementPlugin = True
            self.plugin_name = MMTDefinitions.CONST_SETTINGS_PLUGIN_NAME
        self.setupUi(self)
        self.pluginPointCloudToolsInstance = utils.plugins['point_cloud_tools']
        self.pluginPhotogrammetryToolsInstance = utils.plugins['photogrammetry_tools']
        self.initialize()

    def addPhotogrammetryConnection(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        items = []
        items.append(MMTDefinitions.CONST_NO_COMBO_SELECT)
        self.getPhotogrammetrySpatialiteConnections()
        for connection in self.photogrammetryConnections.keys():
            if not connection in self.photogrammetryConnectionsInProject:
                items.append(connection)
        item, ok = QInputDialog.getItem(self, "Select Photogrammetry Project",
                                    "Photogrammetry Project:", items, 0, False)
        if ok and item:
            if item == MMTDefinitions.CONST_NO_COMBO_SELECT:
                return
            connectionName = item
            photogrammetrySpatialiteDbFileName = self.photogrammetryConnections[connectionName]
            ret = self.iPyProject.mmtAddPhotogrammetryDb(dbFileName,
                                                         photogrammetrySpatialiteDbFileName)
            if ret[0] == "False":
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Error:\n"+ret[1])
                msgBox.exec_()
                return
            else:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Process completed successfully")
                msgBox.exec_()
            self.photogrammetryConnectionsInProject[connectionName] = photogrammetrySpatialiteDbFileName
            self.photogrammetriesComboBox.clear()
            self.photogrammetriesComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
            for photogrammetryConnectionInProject in self.photogrammetryConnectionsInProject.keys():
                self.photogrammetriesComboBox.addItem(photogrammetryConnectionInProject)
        return

    def addPointCloudConnection(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        items = []
        items.append(MMTDefinitions.CONST_NO_COMBO_SELECT)
        self.getPointCloudSpatialiteConnections()
        for pointCloudConnection in self.pointCloudConnections.keys():
            if not pointCloudConnection in self.pointCloudConnectionsInProject:
                items.append(pointCloudConnection)
        item, ok = QInputDialog.getItem(self, "Select Point Cloud",
                                    "Point Cloud:", items, 0, False)
        if ok and item:
            if item == MMTDefinitions.CONST_NO_COMBO_SELECT:
                return
            connectionName = item
            pointCloudSpatialiteDbFileName = self.pointCloudConnections[connectionName]
            ret = self.iPyProject.mmtAddPointCloudDb(dbFileName,
                                                     pointCloudSpatialiteDbFileName)
            if ret[0] == "False":
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Error:\n"+ret[1])
                msgBox.exec_()
                return
            else:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Process completed successfully")
                msgBox.exec_()
            self.pointCloudConnectionsInProject[connectionName] = pointCloudSpatialiteDbFileName
            self.pointCloudsComboBox.clear()
            self.pointCloudsComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
            for pointCloudConnectionInProject in self.pointCloudConnectionsInProject.keys():
                self.pointCloudsComboBox.addItem(pointCloudConnectionInProject)
        return

    def addPowerlinesFromShpProcess(self):
        altitudeIsMsl = True
        if self.plsfAltitudeEllipsoidRadioButton.isChecked():
            altitudeIsMsl = False
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        if len(self.powerlinesFiles) == 0:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select power lines files")
            msgBox.exec_()
            return
        strPowerlinesFiles = ''
        cont = 0
        for powerlineFile in self.powerlinesFiles:
            if cont > 0:
                strPowerlinesFiles = strPowerlinesFiles + self.parametersFromPythonStringSeparator
            strPowerlinesFiles = strPowerlinesFiles + powerlineFile
            cont = cont + 1
        strPowerlinesNameInput = ""
        if self.plsfNameInputRadioButton.isChecked():
            strPowerlinesNameInput = self.plsfNameInputLineEdit.text()
            if not strPowerlinesNameInput:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Input name for powerlines")
                msgBox.exec_()
                return
        strPowerlinesFieldName = ""
        if self.plsfNameFieldRadioButton.isChecked():
            strPowerlinesFieldName = self.plsfNameFieldLineEdit.text()
            if not strPowerlinesFieldName:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Input field name for powerlines")
                msgBox.exec_()
                return
        strMinimumDistanceBetweenElectricPylons = self.plsfElectricPylonsMinimumDistanceLineEdit.text()
        if not strMinimumDistanceBetweenElectricPylons:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select minimum distance between electric pylons")
            msgBox.exec_()
            return
        strElectricPylonsBaseRadius = self.plsfElectricPylonsBaseRadiusLineEdit.text()
        if not strElectricPylonsBaseRadius:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select electric pylons base radius")
            msgBox.exec_()
            return
        strElectricPylonsHeight = self.plsfElectricPylonsHeightLineEdit.text()
        if not strElectricPylonsHeight:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select electric pylons height")
            msgBox.exec_()
            return
        ret = self.iPyProject.mmtAddPowerlinesFiles(dbFileName,
                                                    altitudeIsMsl,
                                                    strPowerlinesNameInput,
                                                    strPowerlinesFiles,
                                                    strPowerlinesFieldName,
                                                    strMinimumDistanceBetweenElectricPylons,
                                                    strElectricPylonsBaseRadius,
                                                    strElectricPylonsHeight)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        else:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Process completed successfully")
            msgBox.exec_()
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_POWERLINE.lower():
            self.loadElectricPylonsLayer()
            self.loadElectricPylonsConnectionsLayer()
        return

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    def closeProject(self):
        if not self.dbFileName:
            return
        self.openProjectPushButton.setEnabled(False)
        self.closeProjectPushButton.setEnabled(False)
        # delete project in ram??
        root = QgsProject.instance().layerTreeRoot()
        self.removeGroup(root,self.layerTreeProjectName)
        self.dbFileName = None
        self.layerTreeProjectName = None
        self.layerTreeProject = None
        # self.layerTreePCTilesName = None
        # self.layerTreePCTiles = None
        self.projectsComboBox.setEnabled(True)
        self.projectsComboBox.setCurrentIndex(0)
        self.iface.mapCanvas().refresh()
        self.processingToolsPage.setEnabled(False)
        self.pointCloudsComboBox.clear()
        self.processCommandComboBox.clear()
        return

    def createProject(self):
        projectType = self.projectTypeComboBox.currentText()
        if projectType == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select project type")
            msgBox.exec_()
            return
        crs = self.projectQgsProjectionSelectionWidget.crs()
        isValidCrs = crs.isValid()
        crsAuthId = crs.authid()
        if not "EPSG:" in crsAuthId:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Selected CRS is not EPSG")
            msgBox.exec_()
            return
        crsEpsgCode = int(crsAuthId.replace('EPSG:',''))
        crsOsr = osr.SpatialReference()  # define test1
        if crsOsr.ImportFromEPSG(crsEpsgCode) != 0:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error importing OSR CRS from EPSG code" + str(crsEpsgCode))
            msgBox.exec_()
            return
        if not crsOsr.IsProjected():
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Selected CRS is not a projected CRS")
            msgBox.exec_()
            return
        altitudeIsMsl = True
        if self.projectAltitudeEllipsoidRadioButton.isChecked():
            altitudeIsMsl = False
        dbFileName = self.databaseLineEdit.text()
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        strRoisShapefiles = ''
        cont = 0
        for roiShapefile in self.roisShapefiles:
            if cont > 0:
                strRoisShapefiles = strRoisShapefiles + self.parametersFromPythonStringSeparator
            strRoisShapefiles = strRoisShapefiles + roiShapefile
            cont = cont + 1
        ret = self.iPyProject.mmtCreateProject(dbFileName,
                                               projectType,
                                               crsEpsgCode,
                                               altitudeIsMsl,
                                               strRoisShapefiles)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        connectionName = QFileInfo(dbFileName).fileName()
        con = [connectionName, dbFileName]
        QSettings().setValue("SpatiaLite/connections/%s/sqlitepath" % (con[0]), con[1])
        self.iface.reloadConnections()
        self.getModelManagementSpatialiteConnections()
        msgBox = QMessageBox(self)
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setWindowTitle(self.windowTitle)
        msgBox.setText("Process completed successfully")
        msgBox.exec_()
        return

    def getModelManagementSpatialiteConnections(self):
        self.modelManagementConnections = {}
        settings = QSettings()
        settings.beginGroup('/SpatiaLite/connections')
        list_str_keys = settings.allKeys()
        paths = []
        for key in list_str_keys:
            if key!= 'selected':
                paths.append(settings.value(key))
        ret = self.iPyProject.getModelDbSpatialiteDbs(paths)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            self.pmTemporalPathLineEdit.setText("")
            self.projectManagerTemporalPath = None
            return
        connectionNames = settings.childGroups()
        cont = 0
        for connectionName in connectionNames:
            path = paths[cont]
            if path in ret:
                self.modelManagementConnections[connectionName] = paths[cont]
            cont = cont + 1
        self.projectsComboBox.clear()
        self.projectsComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        for connection in self.modelManagementConnections.keys():
            self.projectsComboBox.addItem(connection)
        return

    def getCommands(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        ret = self.iPyProject.mmtGetCommands(dbFileName)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            return
        commands = []
        cont = 0
        for value in ret:
            if cont > 0:
                commands.append(value)
            cont = cont + 1
        self.processCommandComboBox.clear()
        self.processCommandComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        for pointCloudCommand in commands:
            self.processCommandComboBox.addItem(pointCloudCommand)
        return

    def getPhotogrammetrySpatialiteConnections(self):
        self.photogrammetryConnections = {}
        settings = QSettings()
        settings.beginGroup('/SpatiaLite/connections')
        list_str_keys = settings.allKeys()
        paths = []
        for key in list_str_keys:
            paths.append(settings.value(key))
        ret = self.iPyProject.getPhotogrammetrySpatialiteDbs(paths)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            self.pmTemporalPathLineEdit.setText("")
            self.projectManagerTemporalPath = None
            return
        connectionNames = settings.childGroups()
        cont = 0
        for connectionName in connectionNames:
            path = paths[cont]
            if path in ret:
                self.photogrammetryConnections[connectionName] = paths[cont]
            cont = cont + 1
        # self.pointCloudsComboBox.clear()
        # self.pointCloudsComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        # for pointCloudConnection in self.pointCloudConnections.keys():
        #     self.pointCloudsComboBox.addItem(pointCloudConnection)
        # return

    def getPointCloudSpatialiteConnections(self):
        self.pointCloudConnections = {}
        settings = QSettings()
        settings.beginGroup('/SpatiaLite/connections')
        list_str_keys = settings.allKeys()
        paths = []
        for key in list_str_keys:
            paths.append(settings.value(key))
        ret = self.iPyProject.getPointCloudSpatialiteDbs(paths)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            self.pmTemporalPathLineEdit.setText("")
            self.projectManagerTemporalPath = None
            return
        connectionNames = settings.childGroups()
        cont = 0
        for connectionName in connectionNames:
            path = paths[cont]
            if path in ret:
                self.pointCloudConnections[connectionName] = paths[cont]
            cont = cont + 1
        # self.pointCloudsComboBox.clear()
        # self.pointCloudsComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        # for pointCloudConnection in self.pointCloudConnections.keys():
        #     self.pointCloudsComboBox.addItem(pointCloudConnection)
        # return

    def getPhotogrammetrySpatialiteConnectionsInProject(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        self.photogrammetryConnectionsInProject = {}
        ret = self.iPyProject.mmtGetPhotogrammetrySpatialiteDbsInProject(dbFileName)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            return
        self.getPhotogrammetrySpatialiteConnections()
        for photogrammetryConnection in self.photogrammetryConnections.keys():
            path = self.photogrammetryConnections[photogrammetryConnection]
            if path in ret:
                self.photogrammetryConnectionsInProject[photogrammetryConnection] = path
        self.photogrammetriesComboBox.clear()
        self.photogrammetriesComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        for photogrammetryConnectionInProject in self.photogrammetryConnectionsInProject.keys():
            self.photogrammetriesComboBox.addItem(photogrammetryConnectionInProject)
        return

    def getPointCloudSpatialiteConnectionsInProject(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        self.pointCloudConnectionsInProject = {}
        ret = self.iPyProject.mmtGetPointCloudSpatialiteDbsInProject(dbFileName)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            return
        self.getPointCloudSpatialiteConnections()
        for pointCloudConnection in self.pointCloudConnections.keys():
            path = self.pointCloudConnections[pointCloudConnection]
            if path in ret:
                self.pointCloudConnectionsInProject[pointCloudConnection] = path
        self.pointCloudsComboBox.clear()
        self.pointCloudsComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        for pointCloudConnectionInProject in self.pointCloudConnectionsInProject.keys():
            self.pointCloudsComboBox.addItem(pointCloudConnectionInProject)
        return

    def initialize(self):
        self.num_format = re.compile(r'^\-?[1-9][0-9]*\.?[0-9]*')
        self.dbFileName = None
        self.layerTreeName = None
        self.layerTree = None
        self.projectType = None
        self.modelManagementConnections = {}
        self.pointCloudConnections = {}
        self.pointCloudConnectionsInProject = {}
        self.photogrammetryConnections = {}
        self.photogrammetryConnectionsInProject = {}
        self.imageFileNamesByHotspotName = {}
        # self.path_plugin = pluginPath
        # self.path_libCpp = libCppPath
        self.windowTitle = MMTDefinitions.CONST_PROGRAM_NAME
        # path_file_qsettings = self.path_plugin + '/' + MMTDefinitions.CONST_SETTINGS_FILE_NAME
        # self.settings = QSettings(path_file_qsettings,QSettings.IniFormat)
        self.path = self.settings.value("last_path")
        if not self.path:
            self.path = QDir.currentPath()
            self.settings.setValue("last_path",self.path)
            self.settings.sync()

        self.projectManagerTemporalPath = self.settings.value("project_management_temporal_path")
        auxDir = QDir(self.path)
        if not self.projectManagerTemporalPath or not auxDir.exists(self.projectManagerTemporalPath):
            self.projectManagerTemporalPath = self.path_libCpp + MMTDefinitions.CONST_PROJECT_MANAGEMENT_TEMPORAL_PATH
            self.settings.setValue("project_management_temporal_path", self.projectManagerTemporalPath)
            self.settings.sync()
        self.pmTemporalPathLineEdit.setText(self.projectManagerTemporalPath)

        self.projectManagerOutputPath = self.settings.value("project_management_output_path")
        auxDir = QDir(self.path)
        if not self.projectManagerOutputPath or not auxDir.exists(self.projectManagerOutputPath):
            self.projectManagerOutputPath = self.path_libCpp + MMTDefinitions.CONST_PROJECT_MANAGEMENT_OUTPUT_PATH
            self.settings.setValue("project_management_output_path", self.projectManagerOutputPath)
            self.settings.sync()
        self.pmOutputPathLineEdit.setText(self.projectManagerOutputPath)

        qs = QSettings()
        spatialiteConnections = qs.value("SpatiaLite/connections")

        # template path que cuelga del directorio de este fichero
        pluginsPath = QFileInfo(QgsApplication.qgisUserDatabaseFilePath()).path()
        thisFilePath = os.path.dirname(os.path.realpath(__file__))
        thisFilePath = os.path.join(pluginsPath, thisFilePath)
        # templatePath = os.path.join(thisFilePath, PCTDefinitions.CONST_TEMPLATE_PATH)
        self.templatePath = thisFilePath + MMTDefinitions.CONST_TEMPLATE_PATH
        svg_paths = qs.value('svg/searchPathsForSVG')
        # if self.templatePath not in svg_paths:
            # qs.setValue('svg/searchPathsForSVG', svg_paths + [self.templatePath])
        qs.setValue('svg/searchPathsForSVG', self.templatePath)
        # if not svg_paths:
            # qs.setValue('svg/searchPathsForSVG', self.templatePath)
        # else:
            # qs.setValue('svg/searchPathsForSVG', svg_paths + [self.templatePath])

        # self.qmlPointCloudFileName = self.templatePath + PCTDefinitions.CONST_SYMBOLOGY_POINT_CLOUD_TEMPLATE
        # self.qmlTilesFileName = self.templatePath + PTDefinitions.CONST_SYMBOLOGY_TILES_TEMPLATE
        self.qmlRoisFileName = self.templatePath + MMTDefinitions.CONST_SYMBOLOGY_ROIS_TEMPLATE
        # self.qmlImagesPcFileName = self.templatePath + PTDefinitions.CONST_SYMBOLOGY_IMAGES_PC
        self.qmlElectricPylonsFileName = self.templatePath + MMTDefinitions.CONST_SYMBOLOGY_ELECTRIC_PYLONS_TEMPLATE
        self.qmlElectricPylonsConnectionsFileName = self.templatePath + MMTDefinitions.CONST_SYMBOLOGY_ELECTRIC_PYLONS_CONNECTIONS_TEMPLATE
        self.qmlPhotovoltaicArrayPanelsFileName = self.templatePath + MMTDefinitions.CONST_SYMBOLOGY_PHOTOVOLTAIC_ARRAY_PANELS_TEMPLATE
        ret = self.iPyProject.setModelDbManager()
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return

        ret = self.iPyProject.setPointCloudDbManager()
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return

        ret = self.iPyProject.setPhotogrammetryManager()
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return

        # self.iPyModelManagementToolsProject=IPyModelManagementToolsProject()
        # self.iPyModelManagementToolsProject.setPythonModulePath(libCppPath)
        # ret = self.iPyModelManagementToolsProject.initialize()
        self.parametersFromPythonStringSeparator = self.iPyProject.getParametersFromPythonStringSeparator()
        ret = self.iPyProject.mmtSetProjectManagerTemporalPath(self.projectManagerTemporalPath)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            self.pmTemporalPathLineEdit.setText("")
            self.projectManagerTemporalPath = None
            return
        ret = self.iPyProject.mmtSetProjectManagerOutputPath(self.projectManagerOutputPath)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            self.pmOutputPathLineEdit.setText("")
            self.projectManagerOutputPath = None
            return

        self.roisShapefiles = []
        self.roisFileTypes = []
        self.roisFileTypes.append(MMTDefinitions.CONST_DOCUMENTS_TYPE_SHAPEFILE)
        self.roisFilesActiveFileExtensions = self.roisFileTypes

        self.powerlinesFiles = []
        self.powerlinesFilesFileTypes = []
        self.powerlinesFilesFileTypes.append(MMTDefinitions.CONST_DOCUMENTS_TYPE_SHAPEFILE)
        # self.powerLinesFilesFileTypes.append(PCTDefinitions.CONST_DOCUMENTS_TYPE_LAZFILE)
        self.powerlinesFilesActiveFileExtensions = self.powerlinesFilesFileTypes

        self.solarParkFiles = []
        self.solarParkFilesFileTypes = []
        self.solarParkFilesFileTypes.append(MMTDefinitions.CONST_DOCUMENTS_TYPE_SHAPEFILE)
        # self.powerLinesFilesFileTypes.append(PCTDefinitions.CONST_DOCUMENTS_TYPE_LAZFILE)
        self.solarParkFilesActiveFileExtensions = self.solarParkFilesFileTypes

        self.layerTreeProject = None
        self.layerTreeProjectName = None
        # self.layerTreePCTiles = None
        # self.layerTreePCTilesName = None
        # self.loadedTiles = []

        # set projectManagement active
        self.modelManagementToolBox.setCurrentIndex(0)

        self.modelManagementToolBox.currentChanged.connect(self.onModelManagementToolBoxChanged)

        ###################################################
        # Project Management Page
        ###################################################

        # Projects spatialite databases
        self.getModelManagementSpatialiteConnections()
        self.projectsComboBox.currentIndexChanged.connect(self.selectProject)

        # Project
        self.openProjectPushButton.clicked.connect(self.openProject)
        self.closeProjectPushButton.clicked.connect(self.closeProject)

        self.projectManagementTabWidget.currentChanged.connect(self.onProjectManagementTabWidgetChanged)

        # Project types
        self.projecTypes = self.iPyProject.mmtGetProjectTypes()
        self.projectTypeComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        for projectType in self.projecTypes:
            self.projectTypeComboBox.addItem(projectType)
        self.projectTypeComboBox.currentIndexChanged.connect(self.selectProjectType)

        # Parameters
        self.projectParametersPushButton.clicked.connect(self.selectProjectParameters)

        # DbFile
        self.databasePushButton.clicked.connect(self.selectNewDatabase)

        self.projectManagementTabWidget.setTabEnabled(0,True)
        self.projectManagementTabWidget.setTabEnabled(1,False)
        self.projectManagementTabWidget.setTabEnabled(2,False)
        self.projectManagementTabWidget.setTabEnabled(3,False)
        self.projectManagementTabWidget.setCurrentIndex(0)
        self.openProjectPushButton.setEnabled(False)
        self.closeProjectPushButton.setEnabled(False)

        # ROIs
        self.roisPushButton.clicked.connect(self.selectRois)
        self.numberOfRoisLineEdit.setText("0")

        # create
        self.createProjectPushButton.clicked.connect(self.createProject)

        self.selectPLSFsPushButton.clicked.connect(self.selectPLSFs)
        self.plsfNameShpRadioButton.clicked.connect(self.selectPLSFNameShp)
        self.plsfNameInputRadioButton.clicked.connect(self.selectPLSFNameInput)
        self.plsfNameFieldRadioButton.clicked.connect(self.selectPLSFNameField)
        self.plsfNameInputPushButton.clicked.connect(self.selectPLSFNameInputValue)
        self.plsfNameFieldPushButton.clicked.connect(self.selectPLSDNameFieldValue)

        self.plsfElectricPylonsMinimumDistancePushButton.clicked.connect(self.selectMinimumDistanceBetweenElectricPylons)
        self.plsfElectricPylonsBaseRadiusPushButton.clicked.connect(self.selectElectricPylonsBaseRadius)
        self.plsfElectricPylonsHeightPushButton.clicked.connect(self.selectElectricPylonsHeight)

        self.plsfProcessPushButton.clicked.connect(self.addPowerlinesFromShpProcess)

        self.selectSPSFsPushButton.clicked.connect(self.selectSPSFs)
        self.spdSelectSFFieldsPushButton.clicked.connect(self.selectSPSFFields)
        self.spsfProcessPushButton.clicked.connect(self.spsfProcess)

        # temporal path
        self.pmTemporalPathPushButton.clicked.connect(self.selectProjectManagerTemporalPath)
        self.pmOutputPathPushButton.clicked.connect(self.selectProjectManagerOutputPath)

        self.processingToolsPage.setEnabled(False)

        ###################################################
        # Processing ToolsPage
        ###################################################
        self.addPointCloudPushButton.clicked.connect(self.addPointCloudConnection)
        self.removePointCloudPushButton.clicked.connect(self.removePointCloudConnection)
        self.openPointCloudPushButton.clicked.connect(self.openPointCloud)

        self.addPhotogrammetryPushButton.clicked.connect(self.addPhotogrammetryConnection)
        self.removePhotogrammetryPushButton.clicked.connect(self.removePhotogrammetryConnection)
        self.openPhotogrammetryPushButton.clicked.connect(self.openPhotogrammetry)
        self.openPhotogrammetryPushButton.setEnabled(False)

        self.processCommandComboBox.currentIndexChanged.connect(self.selectCommand)
        self.commandParamtersPushButton.clicked.connect(self.selectCommandParameters)
        self.processCommandPushButton.clicked.connect(self.selectCommandProcess)
        self.processCommandPushButton.setEnabled(False)
        self.reportGroupBox.setVisible(False)
        self.reportArrayComboBox.currentIndexChanged.connect(self.selectReportArray)
        self.reportProcessPushButton.clicked.connect(self.selectReportProcess)
        self.reportUpdatePushButton.clicked.connect(self.selectUpdateReferenceLayers)
        self.reportHotspotComboBox.currentIndexChanged.connect(self.selectReportHotspot)

    def loadElectricPylonsLayer(self):
        electricPylonsTableName = MMTDefinitions.CONST_SPATIALITE_LAYERS_ELECTRIC_PYLONS_TABLE_NAME
        layerList = QgsProject.instance().mapLayersByName(electricPylonsTableName)
        if not layerList:
            uri = QgsDataSourceUri()
            uri.setDatabase(self.dbFileName)
            schema = ''
            table = electricPylonsTableName
            geom_column = MMTDefinitions.CONST_SPATIALITE_LAYERS_ELECTRIC_PYLONS_TABLE_GEOMETRY_COLUMN
            uri.setDataSource(schema, table, geom_column)
            display_name = electricPylonsTableName
            vlayer = QgsVectorLayer(uri.uri(), display_name, 'spatialite')
            if vlayer.isValid():
                # if vlayer.featureCount() == 0:
                #     return
                QgsProject.instance().addMapLayer(vlayer,False)
                self.layerTreeProject.insertChildNode(1, QgsLayerTreeLayer(vlayer))
                vlayer.loadNamedStyle(self.qmlElectricPylonsFileName)
                vlayer.triggerRepaint()
                self.iface.setActiveLayer(vlayer)
                self.iface.zoomToActiveLayer()
            else:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Impossible to Load table: " + electricPylonsTableName
                                   +" into QGIS")
                msgBox.exec_()

    def loadElectricPylonsConnectionsLayer(self):
        electricPylonsConnectionsTableName = MMTDefinitions.CONST_SPATIALITE_LAYERS_ELECTRIC_PYLONS_CONNECTIONS_TABLE_NAME
        layerList = QgsProject.instance().mapLayersByName(electricPylonsConnectionsTableName)
        if not layerList:
            uri = QgsDataSourceUri()
            uri.setDatabase(self.dbFileName)
            schema = ''
            table = electricPylonsConnectionsTableName
            geom_column = MMTDefinitions.CONST_SPATIALITE_LAYERS_ELECTRIC_PYLONS_CONNECTIONS_TABLE_GEOMETRY_COLUMN
            uri.setDataSource(schema, table, geom_column)
            display_name = electricPylonsConnectionsTableName
            vlayer = QgsVectorLayer(uri.uri(), display_name, 'spatialite')
            if vlayer.isValid():
                # if vlayer.featureCount() == 0:
                #     return
                QgsProject.instance().addMapLayer(vlayer,False)
                self.layerTreeProject.insertChildNode(1, QgsLayerTreeLayer(vlayer))
                vlayer.loadNamedStyle(self.qmlElectricPylonsConnectionsFileName)
                vlayer.triggerRepaint()
                self.iface.setActiveLayer(vlayer)
                self.iface.zoomToActiveLayer()
            else:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Impossible to Load table: " + electricPylonsConnectionsTableName
                                   +" into QGIS")
                msgBox.exec_()

    def loadPhotovoltaicArrayPanels(self):
        photovoltaicArrayPanelsTableName = MMTDefinitions.CONST_SPATIALITE_LAYERS_PHOTOVOLTAIC_ARRAY_PANELS_TABLE_NAME
        layerList = QgsProject.instance().mapLayersByName(photovoltaicArrayPanelsTableName)
        if not layerList:
            uri = QgsDataSourceUri()
            uri.setDatabase(self.dbFileName)
            schema = ''
            table = photovoltaicArrayPanelsTableName
            geom_column = MMTDefinitions.CONST_SPATIALITE_LAYERS_PHOTOVOLTAIC_ARRAY_PANELS_TABLE_GEOMETRY_COLUMN
            uri.setDataSource(schema, table, geom_column)
            display_name = photovoltaicArrayPanelsTableName
            vlayer = QgsVectorLayer(uri.uri(), display_name, 'spatialite')
            if vlayer.isValid():
                # if vlayer.featureCount() == 0:
                #     return
                QgsProject.instance().addMapLayer(vlayer,False)
                self.layerTreeProject.insertChildNode(1, QgsLayerTreeLayer(vlayer))
                vlayer.loadNamedStyle(self.qmlPhotovoltaicArrayPanelsFileName)
                vlayer.triggerRepaint()
                self.iface.setActiveLayer(vlayer)
                self.iface.zoomToActiveLayer()
            else:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Impossible to Load table: " + photovoltaicArrayPanelsTableName
                                   +" into QGIS")
                msgBox.exec_()


    def loadROIsLayer(self):
        roisTableName = MMTDefinitions.CONST_SPATIALITE_LAYERS_ROIS_TABLE_NAME
        layerList = QgsProject.instance().mapLayersByName(roisTableName)
        if not layerList:
            uri = QgsDataSourceUri()
            uri.setDatabase(self.dbFileName)
            schema = ''
            table = roisTableName
            geom_column = MMTDefinitions.CONST_SPATIALITE_LAYERS_ROIS_TABLE_GEOMETRY_COLUMN
            uri.setDataSource(schema, table, geom_column)
            display_name = roisTableName
            vlayer = QgsVectorLayer(uri.uri(), display_name, 'spatialite')
            if vlayer.isValid():
                # if vlayer.featureCount() == 0:
                #     return
                QgsProject.instance().addMapLayer(vlayer,False)
                self.layerTreeProject.insertChildNode(1, QgsLayerTreeLayer(vlayer))
                vlayer.loadNamedStyle(self.qmlRoisFileName)
                vlayer.triggerRepaint()
                self.iface.setActiveLayer(vlayer)
                self.iface.zoomToActiveLayer()
            else:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Impossible to Load table: " + roisTableName
                                   +" into QGIS")
                msgBox.exec_()

    def onModelManagementToolBoxChanged(self,i): #changed!
        # QMessageBox.information(self,
        #           "Model Management ToolBox Changed!",
        #           "Current Tab Index: %d" % i ) #changed!
        # if i==1: # Point Clouds Projects
        #     self.getPointCloudSpatialiteConnections()
        # yo = 1
        return

    def onProjectManagementTabWidgetChanged(self,i): #changed!
        # QMessageBox.information(self,
        #           "Tab Index Changed!",
        #           "Current Tab Index: %d" % i ) #changed!
        if i==1: # add powerlines
            self.plsfNameShpRadioButton.setChecked(True)
            self.plsfNameInputLineEdit.clear()
            self.plsfNameFieldLineEdit.clear()
            strValueMinimuDistance = MMTDefinitions.CONST_LINEAR_COARSE_PRECISION.format(MMTDefinitions.CONST_POWERLINES_MINIMUM_DISTANCE_BETWEEN_ELECTRIC_PYLONS_DEFAULT_VALUE)
            self.plsfElectricPylonsMinimumDistanceLineEdit.setText(strValueMinimuDistance)
            strValueBaseRadius = MMTDefinitions.CONST_LINEAR_COARSE_PRECISION.format(MMTDefinitions.CONST_POWERLINES_ELECTRIC_PYLONS_BASE_RADIUS_DEFAULT_VALUE)
            self.plsfElectricPylonsBaseRadiusLineEdit.setText(strValueBaseRadius)
            strValueHeight = MMTDefinitions.CONST_LINEAR_COARSE_PRECISION.format(MMTDefinitions.CONST_POWERLINES_ELECTRIC_PYLONS_HEIGHT_DEFAULT_VALUE)
            self.plsfElectricPylonsHeightLineEdit.setText(strValueHeight)
        return

    def openPhotogrammetry(self):
        return

    def openPointCloud(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        selectedPointCloudConnectionInProject = self.pointCloudsComboBox.currentText()
        if selectedPointCloudConnectionInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
            return
        pointCloudSpatialiteDbFileName = self.pointCloudConnectionsInProject[selectedPointCloudConnectionInProject]
        self.pluginPointCloudToolsInstance.runFromAnotherPlugin(self.iface,
                                                                self.path_plugin,
                                                                self.path_libCpp,
                                                                self.plugin_name,
                                                                self.iPyProject,
                                                                selectedPointCloudConnectionInProject)

        layersPanel = [x for x in self.iface.mainWindow().findChildren(QDockWidget) if x.objectName() == 'Layers']
        pctPanel = [x for x in self.iface.mainWindow().findChildren(QDockWidget) if
                    x.objectName() == 'PointCloudToolsDockWidgetBase']
        mmtPanel = [x for x in self.iface.mainWindow().findChildren(QDockWidget) if
                    x.objectName() == 'ModelManagementToolsDockWidgetBase']

        # Para colocar primero en pila vertical y luego unir dos en un tab
        if layersPanel:
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, layersPanel[0])
        self.iface.addDockWidget(Qt.LeftDockWidgetArea, pctPanel[0])
        self.iface.addDockWidget(Qt.LeftDockWidgetArea, mmtPanel[0])
        self.iface.mainWindow().tabifyDockWidget(mmtPanel[0], pctPanel[0])

        # Para que el nobmre de los dos widgets en el tab aparezca en la parte superior
        # esto no va bien
        # iface.mainWindow().setTabPosition(Qt.LeftDockWidgetArea,QTabWidget.South)

        # Para maximizar la ventana principal
        self.iface.mainWindow().showNormal()
        self.iface.mainWindow().showMaximized()
        self.iface.mainWindow().update()
        return

    def openProject(self):
        self.closeProjectPushButton.setEnabled(False)
        self.dbFileName = None
        self.layerTreeName = None
        self.layerTree = None
        connectionFileName = self.projectsComboBox.currentText()
        if connectionFileName == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select project before")
            msgBox.exec_()
            return
        connectionPath = self.modelManagementConnections[connectionFileName]
        ret = self.iPyProject.mmtOpenProject(connectionPath)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            self.projectsComboBox.setCurrentIndex(0)
            return
        ret = self.iPyProject.mmtGetProjectCrsEpsgCode(connectionPath)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            self.projectsComboBox.setCurrentIndex(0)
            return
        self.crsEpsgCode = ret[1]
        ret = self.iPyProject.mmtGetProjectType(connectionPath)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            self.projectsComboBox.setCurrentIndex(0)
            return
        self.projectType = ret[1]
        self.dbFileName = connectionPath
        groupName = MMTDefinitions.CONST_LAYER_TREE_PROJECT_NAME
        self.layerTreeProjectName = groupName + connectionFileName
        root = QgsProject.instance().layerTreeRoot()
        self.layerTreeProject = root.addGroup(self.layerTreeProjectName)
        self.loadROIsLayer()
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_POWERLINE.lower():
            self.loadElectricPylonsLayer()
            self.loadElectricPylonsConnectionsLayer()
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_SOLARPARK.lower():
            self.loadPhotovoltaicArrayPanels()
        # self.loadTilesLayer()
        self.closeProjectPushButton.setEnabled(True)
        self.openProjectPushButton.setEnabled(False)
        self.projectsComboBox.setEnabled(False)
        self.projectManagementTabWidget.setEnabled(True)
        self.projectManagementTabWidget.setTabEnabled(0, False)
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_POWERLINE.lower():
            self.projectManagementTabWidget.setTabEnabled(1, True)
            self.projectManagementTabWidget.setTabEnabled(2, False)
            self.plsfNameShpRadioButton.setChecked(True)
            self.selectPLSFNameShp()
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_SOLARPARK.lower():
            self.projectManagementTabWidget.setTabEnabled(1, False)
            self.projectManagementTabWidget.setTabEnabled(2, True)
            self.spdSelectSFFieldsPushButton.setEnabled(False)
            self.spsfProcessPushButton.setEnabled(False)
        # tilesTableName = PCTDefinitions.CONST_SPATIALITE_LAYERS_TILES_TABLE_NAME
        # layerList = QgsProject.instance().mapLayersByName(tilesTableName)
        # if not layerList:
        #     self.projectManagementTabWidget.setTabEnabled(2, False)
        # else:
        #     tilesLayer = layerList[0]
        #     if tilesLayer.featureCount() > 0:
        #         self.projectManagementTabWidget.setTabEnabled(2, True)
        self.processingToolsPage.setEnabled(True)
        self.getPointCloudSpatialiteConnectionsInProject()
        self.getPhotogrammetrySpatialiteConnectionsInProject()
        self.getCommands()
        # # msgBox = QMessageBox(self)
        # # msgBox.setIcon(QMessageBox.Information)
        # # msgBox.setWindowTitle(self.windowTitle)
        # # msgBox.setText("Process completed successfully")
        # # msgBox.exec_()
        return

    def removeGroup(self,root,name):
        # root = QgsProject.instance().layerTreeRoot()
        group = root.findGroup(name)
        if not group is None:
            for child in group.children():
                dump = child.dump()
                id = dump.split("=")[-1].strip()
                QgsProject.instance().removeMapLayer(id)
            root.removeChildNode(group)

    def selectNewDatabase(self):
        oldFileName=self.databaseLineEdit.text()
        title="Select New Project File (.sqlite)"
        filters="Project Files (*.sqlite)"
        fileName, _ = QFileDialog.getSaveFileName(self,title,self.path,filters)
        if fileName:
            fileInfo = QFileInfo(fileName)
            self.path = fileInfo.absolutePath()
            self.databaseLineEdit.setText(fileName)
            self.settings.setValue("last_path", self.path)
            self.settings.sync()
        return

    def removePhotogrammetryConnection(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        selectedPhotogrammetryConnectionInProject = self.photogrammetriesComboBox.currentText()
        if selectedPhotogrammetryConnectionInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
            return
        photogrammetrySpatialiteDbFileName = self.photogrammetryConnectionsInProject[selectedPhotogrammetryConnectionInProject]
        ret = self.iPyProject.mmtRemovePhotogrammetryDb(dbFileName,
                                                        photogrammetrySpatialiteDbFileName)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        else:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Process completed successfully")
            msgBox.exec_()
        del self.photogrammetryConnectionsInProject[selectedPhotogrammetryConnectionInProject]
        self.photogrammetriesComboBox.clear()
        self.photogrammetriesComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        for photogrammetryConnectionInProject in self.photogrammetryConnectionsInProject.keys():
            self.photogrammetriesComboBox.addItem(photogrammetryConnectionInProject)
        return

    def removePointCloudConnection(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        selectedPointCloudConnectionInProject = self.pointCloudsComboBox.currentText()
        if selectedPointCloudConnectionInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
            return
        pointCloudSpatialiteDbFileName = self.pointCloudConnectionsInProject[selectedPointCloudConnectionInProject]
        ret = self.iPyProject.mmtRemovePointCloudDb(dbFileName,
                                                    pointCloudSpatialiteDbFileName)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        else:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Process completed successfully")
            msgBox.exec_()
        del self.pointCloudConnectionsInProject[selectedPointCloudConnectionInProject]
        self.pointCloudsComboBox.clear()
        self.pointCloudsComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        for pointCloudConnectionInProject in self.pointCloudConnectionsInProject.keys():
            self.pointCloudsComboBox.addItem(pointCloudConnectionInProject)
        return

    def selectElectricPylonsBaseRadius(self):
        strCandidateValue = self.plsfElectricPylonsBaseRadiusLineEdit.text()
        label = "Input electric pylons base radius (m):"
        title = MMTDefinitions.CONST_POWERLINES_BASE_RADIUS_ELECTRIC_PYLONS_TITLE
        ok = False
        while not ok:
            [text, ok] = QInputDialog.getText(self, title, label, QLineEdit.Normal, strCandidateValue)
            if ok and text:
                value = 0.0
                text = text.strip()
                if text.isdigit() or re.match(self.num_format,text):
                    value = float(text)
                    if (value < MMTDefinitions.CONST_POWERLINES_BASE_RADIUS_ELECTRIC_PYLONS_MINIMUM_VALUE
                        or value > MMTDefinitions.CONST_POWERLINES_BASE_RADIUS_ELECTRIC_PYLONS_MAXIMUM_VALUE):
                        ok = False
                else:
                    ok = False
                if ok:
                    strValue=MMTDefinitions.CONST_LINEAR_COARSE_PRECISION.format(value)
                    self.plsfElectricPylonsBaseRadiusLineEdit.setText(strValue)
            else:
                if not ok:
                    ok = True

    def selectElectricPylonsHeight(self):
        strCandidateValue = self.plsfElectricPylonsHeightLineEdit.text()
        label = "Input electric pylons base radius (m):"
        title = MMTDefinitions.CONST_POWERLINES_HEIGHT_ELECTRIC_PYLONS_TITLE
        ok = False
        while not ok:
            [text, ok] = QInputDialog.getText(self, title, label, QLineEdit.Normal, strCandidateValue)
            if ok and text:
                value = 0.0
                text = text.strip()
                if text.isdigit() or re.match(self.num_format,text):
                    value = float(text)
                    if (value < MMTDefinitions.CONST_POWERLINES_HEIGHT_ELECTRIC_PYLONS_MINIMUM_VALUE
                        or value > MMTDefinitions.CONST_POWERLINES_HEIGHT_ELECTRIC_PYLONS_MAXIMUM_VALUE):
                        ok = False
                else:
                    ok = False
                if ok:
                    strValue=MMTDefinitions.CONST_LINEAR_COARSE_PRECISION.format(value)
                    self.plsfElectricPylonsHeightLineEdit.setText(strValue)
            else:
                if not ok:
                    ok = True

    def selectMinimumDistanceBetweenElectricPylons(self):
        strCandidateValue = self.plsfElectricPylonsMinimumDistanceLineEdit.text()
        label = "Input minimum distance (m):"
        title = MMTDefinitions.CONST_POWERLINES_MINIMUM_DISTANCE_BETWEEN_ELECTRIC_PYLONS_TITLE
        ok = False
        while not ok:
            [text, ok] = QInputDialog.getText(self, title, label, QLineEdit.Normal, strCandidateValue)
            if ok and text:
                value = 0.0
                text = text.strip()
                if text.isdigit() or re.match(self.num_format,text):
                    value = float(text)
                    if (value < MMTDefinitions.CONST_POWERLINES_MINIMUM_DISTANCE_BETWEEN_ELECTRIC_PYLONS_MINIMUM_VALUE
                        or value > MMTDefinitions.CONST_POWERLINES_MINIMUM_DISTANCE_BETWEEN_ELECTRIC_PYLONS_MAXIMUM_VALUE):
                        ok = False
                else:
                    ok = False
                if ok:
                    strValue=MMTDefinitions.CONST_LINEAR_COARSE_PRECISION.format(value)
                    self.plsfElectricPylonsMinimumDistanceLineEdit.setText(strValue)
            else:
                if not ok:
                    ok = True

    def selectPLSFNameField(self):
        if self.plsfNameFieldRadioButton.isChecked():
            self.plsfNameInputPushButton.setEnabled(False)
            self.plsfNameInputLineEdit.clear()
            self.plsfNameFieldPushButton.setEnabled(True)
            self.plsfNameFieldLineEdit.clear()
        return

    def selectPLSFs(self):
        previousFiles = self.powerlinesFiles[:] # copia desligada
        dlg = MultipleFileSelectorDialog(self.iface,
                                         self.path,
                                         MMTDefinitions.CONST_SELECT_POWER_LINES_FILES_DIALOG_TITLE,
                                         self.powerlinesFilesFileTypes,
                                         self.powerlinesFiles,
                                         self.powerlinesFilesActiveFileExtensions)
        dlg.show() # show the dialog
        result = dlg.exec_() # Run the dialog
        self.path = dlg.getPath()
        self.settings.setValue("last_path",self.path)
        files = dlg.getFiles() # los hay repetidos
        self.powerlinesFiles = []
        self.numberOfPLSFsLineEdit.setText("0")
        for file in files:
            fileBaseName = QFileInfo(file).baseName()
            findFile = False
            for pointCloudFile in self.powerlinesFiles:
                if fileBaseName == QFileInfo(pointCloudFile).baseName():
                    findFile = True
                    break
            if not findFile:
                self.powerlinesFiles.append(file)
        self.powerlinesFilesActiveFileExtensions = dlg.getActiveFileExtensions()
        self.numberOfPLSFsLineEdit.setText(str(len(self.powerlinesFiles)))
        return

    def selectPLSDNameFieldValue(self):
        oldText = self.plsfNameFieldLineEdit.text()
        label = "Input field name for power lines readed from shapefiles:"
        title = MMTDefinitions.CONST_PROGRAM_TITLE
        [text, ok] = QInputDialog.getText(self, title, label, QLineEdit.Normal, oldText)
        if ok and text:
            text = text.strip()
            if not text == oldText:
                self.plsfNameFieldLineEdit.setText(text)
        return

    def selectPLSFNameInput(self):
        if self.plsfNameInputRadioButton.isChecked():
            self.plsfNameInputPushButton.setEnabled(True)
            self.plsfNameInputLineEdit.clear()
            self.plsfNameFieldPushButton.setEnabled(False)
            self.plsfNameFieldLineEdit.clear()
        return

    def selectPLSFNameInputValue(self):
        oldText = self.plsfNameInputLineEdit.text()
        label = "Input name for power lines readed from shapefiles:"
        title = MMTDefinitions.CONST_PROGRAM_TITLE
        [text, ok] = QInputDialog.getText(self, title, label, QLineEdit.Normal, oldText)
        if ok and text:
            text = text.strip()
            if not text == oldText:
                self.plsfNameInputLineEdit.setText(text)
        return

    def selectPLSFNameShp(self):
        if self.plsfNameShpRadioButton.isChecked():
            self.plsfNameInputPushButton.setEnabled(False)
            self.plsfNameInputLineEdit.clear()
            self.plsfNameFieldPushButton.setEnabled(False)
            self.plsfNameFieldLineEdit.clear()
        return

    def selectCommandParameters(self):
        command = self.processCommandComboBox.currentText()
        if command == MMTDefinitions.CONST_NO_COMBO_SELECT:
            return
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        ret = self.iPyProject.mmtSelectCommandParameters(dbFileName,command)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        return

    def selectCommand(self):
        self.imageFileNamesByHotspotName.clear()
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        self.reportGroupBox.setVisible(False)
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            self.processCommandPushButton.setEnabled(False)
            return
        command = self.processCommandComboBox.currentText()
        if command == MMTDefinitions.CONST_NO_COMBO_SELECT:
            self.processCommandPushButton.setEnabled(False)
            return
        processCommandIsEnabled = self.iPyProject.mmtGetEnabledProcessCommand(command)
        self.processCommandPushButton.setEnabled(processCommandIsEnabled)
        if command == MMTDefinitions.CONST_SOLARPARK_REPORT_HOT_SPOTS_COMMAND :
            selectedPhotogrammetryInProject = self.photogrammetriesComboBox.currentText()
            if selectedPhotogrammetryInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Select Photogrammetry Project")
                msgBox.exec_()
                self.processCommandComboBox.setCurrentIndex(0)
                return
            photogrammetrySpatialiteDbFileName = self.photogrammetryConnectionsInProject[selectedPhotogrammetryInProject]
            self.reportGroupBox.setVisible(True)
            self.reportReferenceLayerComboBox.clear()
            self.reportReferenceLayerComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
            self.reportArrayComboBox.clear()
            self.reportHotspotComboBox.clear()
            ret = self.iPyProject.mmtGetPhotovoltaicArraysWithAnomalies(dbFileName,
                                                                        photogrammetrySpatialiteDbFileName)
            if ret[0] == "False":
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Error:\n" + ret[1])
                msgBox.exec_()
                self.processCommandComboBox.setCurrentIndex(0)
                return
            arrays = []
            cont = 0
            for value in ret:
                if cont > 0:
                    arrays.append(value)
                cont = cont + 1
            self.reportArrayComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
            self.reportHotspotComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
            for array in arrays:
                self.reportArrayComboBox.addItem(array)
            return

    def selectCommandProcess(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        command = self.processCommandComboBox.currentText()
        if command == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select command to process")
            msgBox.exec_()
            return
        needsPointCloudDb = self.iPyProject.mmtGetCommandNeedsPointCloudDb(command)
        needsPhotogrammetryDb = self.iPyProject.mmtGetCommandNeedsPhotogrammetryDb(command)
        pointCloudSpatialiteDbFileName = ""
        photogrammetrySpatialiteDbFileName = ""
        if needsPointCloudDb:
            selectedPointCloudConnectionInProject = self.pointCloudsComboBox.currentText()
            if selectedPointCloudConnectionInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Select Point Cloud Project")
                msgBox.exec_()
                return
            pointCloudSpatialiteDbFileName = self.pointCloudConnectionsInProject[selectedPointCloudConnectionInProject]
        if needsPhotogrammetryDb:
            selectedPhotogrammetryInProject = self.photogrammetriesComboBox.currentText()
            if selectedPhotogrammetryInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Select Photogrammetry Project")
                msgBox.exec_()
                return
            photogrammetrySpatialiteDbFileName = self.photogrammetryConnectionsInProject[selectedPhotogrammetryInProject]
        ret = self.iPyProject.mmtProcessCommand(dbFileName,command,
                                                pointCloudSpatialiteDbFileName,
                                                photogrammetrySpatialiteDbFileName)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        else:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Process completed successfully")
            msgBox.exec_()
        return

    def selectProject(self):
        self.openProjectPushButton.setEnabled(False)
        self.closeProjectPushButton.setEnabled(False)
        projectFileName = self.projectsComboBox.currentText()
        if projectFileName == MMTDefinitions.CONST_NO_COMBO_SELECT:
            self.projectManagementTabWidget.setEnabled(True)
            self.projectManagementTabWidget.setTabEnabled(0, True)
            self.projectManagementTabWidget.setTabEnabled(1, False)
            self.projectManagementTabWidget.setTabEnabled(2, False)
            self.projectManagementTabWidget.setCurrentIndex(0)
            if self.dbFileName:
                self.closeProject()
        else:
            self.projectManagementTabWidget.setEnabled(False)
            # self.projectManagementTabWidget.setTabEnabled(0, False)
            # self.projectManagementTabWidget.setTabEnabled(1, False)
            # self.projectManagementTabWidget.setTabEnabled(2, False)
            self.projectManagementTabWidget.setCurrentIndex(1)
            self.openProjectPushButton.setEnabled(True)
            self.closeProjectPushButton.setEnabled(False)
        return

    def selectProjectManagerOutputPath(self):
        strDir = QFileDialog.getExistingDirectory(self, "Select directory", self.projectManagerOutputPath,
                                                  QFileDialog.ShowDirsOnly | QFileDialog.DontResolveSymlinks)
        if strDir:
            ret = self.iPyProject.mmtSetProjectManagerOutputPath(self.projectManagerOutputPath)
            if ret[0] == "False":
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Error:\n" + ret[1])
                msgBox.exec_()
                self.pmOutputPathLineEdit.setText("")
                self.projectManagerOutputPath = None
                return
            self.projectManagerOutputPath = strDir
            self.settings.setValue("project_management_output_path", self.projectManagerOutputPath)
            self.settings.sync()
            self.pmOutputPathLineEdit.setText(strDir)
        return

    def selectProjectManagerTemporalPath(self):
        strDir = QFileDialog.getExistingDirectory(self,"Select directory", self.projectManagerTemporalPath,
                                                  QFileDialog.ShowDirsOnly | QFileDialog.DontResolveSymlinks)
        if strDir:
            ret = self.iPyProject.mmtSetProjectManagerTemporalPath(self.projectManagerTemporalPath)
            if ret[0] == "False":
                msgBox = QMessageBox(self)
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setWindowTitle(self.windowTitle)
                msgBox.setText("Error:\n" + ret[1])
                msgBox.exec_()
                self.pmTemporalPathLineEdit.setText("")
                self.projectManagerTemporalPath = None
                return
            self.projectManagerTemporalPath = strDir
            self.settings.setValue("project_management_temporal_path", self.projectManagerTemporalPath)
            self.settings.sync()
            self.pmTemporalPathLineEdit.setText(strDir)
        return

    def selectProjectParameters(self):
        projectType = self.projectTypeComboBox.currentText()
        if projectType == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select project type before")
            msgBox.exec_()
            return
        ret = self.iPyProject.mmtSelectProjectParameters(projectType)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        return

    def selectProjectType(self):
        projectType = self.projectTypeComboBox.currentText()
        # msgBox = QMessageBox(self)
        # msgBox.setIcon(QMessageBox.Information)
        # msgBox.setWindowTitle(self.windowTitle)
        # msgBox.setText("Project type: "+projectType)
        # msgBox.exec_()
        return

    def selectReportArray(self):
        self.imageFileNamesByHotspotName.clear()
        self.reportImageComboBox.clear()
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        self.reportHotspotComboBox.clear()
        self.reportHotspotComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            self.processCommandPushButton.setEnabled(False)
            return
        selectedPhotogrammetryInProject = self.photogrammetriesComboBox.currentText()
        if selectedPhotogrammetryInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Photogrammetry Project")
            msgBox.exec_()
            return
        photogrammetrySpatialiteDbFileName = self.photogrammetryConnectionsInProject[selectedPhotogrammetryInProject]
        array = self.reportArrayComboBox.currentText()
        if array == MMTDefinitions.CONST_NO_COMBO_SELECT:
            self.reportHotspotComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
            return
        ret = self.iPyProject.mmtGetPhotovoltaicArrayAnomalies(dbFileName,
                                                               photogrammetrySpatialiteDbFileName,
                                                               array)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            self.reportArrayComboBox.setCurrentIndex(0)
            return
        cont = 0
        for value in ret:
            if cont > 0:
                self.imageFileNamesByHotspotName = value
            cont = cont + 1
        for hotspotName in self.imageFileNamesByHotspotName:
            self.reportHotspotComboBox.addItem(hotspotName)
        return

    def selectReportHotspot(self):
        self.reportImageComboBox.clear()
        selectedHotspot = self.reportHotspotComboBox.currentText()
        if not selectedHotspot:
            return
        if selectedHotspot == MMTDefinitions.CONST_NO_COMBO_SELECT:
            return
        imageFileNames=self.imageFileNamesByHotspotName[selectedHotspot]
        self.reportImageComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)
        self.reportImageComboBox.addItem(MMTDefinitions.CONST_SOLARPARK_REPORT_HOT_SPOTS_CLOSESTS_IMAGE)
        self.reportImageComboBox.addItem(MMTDefinitions.CONST_SOLARPARK_REPORT_HOT_SPOTS_MOST_ORTHOGONAL_IMAGE)
        for imageFileName in imageFileNames:
            self.reportImageComboBox.addItem(imageFileName)
        return

    def selectReportProcess(self):
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        command = self.processCommandComboBox.currentText()
        if command == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select command to process")
            msgBox.exec_()
            return
        selectedPhotogrammetryInProject = self.photogrammetriesComboBox.currentText()
        if selectedPhotogrammetryInProject == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Photogrammetry Project")
            msgBox.exec_()
            return
        photogrammetrySpatialiteDbFileName = self.photogrammetryConnectionsInProject[selectedPhotogrammetryInProject]
        array = self.reportArrayComboBox.currentText()
        if array == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select array to report")
            msgBox.exec_()
            return
        hotspot = self.reportHotspotComboBox.currentText()
        if hotspot == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select hot spot to report")
            msgBox.exec_()
            return
        imageFileName = self.reportImageComboBox.currentText()
        if imageFileName == MMTDefinitions.CONST_NO_COMBO_SELECT:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select image to report")
            msgBox.exec_()
            return
        ret = self.iPyProject.mmGetPhotovoltaicAnomalyReportData(dbFileName,
                                                                 photogrammetrySpatialiteDbFileName,
                                                                 array,
                                                                 hotspot,
                                                                 imageFileName)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n" + ret[1])
            msgBox.exec_()
            self.reportArrayComboBox.setCurrentIndex(0)
        else:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            strText = "Number of values:" + str(len(ret[1])-1)
            msgBox.setText(strText)
            msgBox.exec_()
        return

    def selectRois(self):
        previousFiles = self.roisShapefiles[:] # copia desligada
        dlg = MultipleFileSelectorDialog(self.iface,
                                         self.path,
                                         MMTDefinitions.CONST_SELECT_ROIS_SHAPEFILES_DIALOG_TITLE,
                                         self.roisFileTypes,
                                         self.roisShapefiles,
                                         self.roisFilesActiveFileExtensions)
        dlg.show() # show the dialog
        result = dlg.exec_() # Run the dialog
        self.path = dlg.getPath()
        self.settings.setValue("last_path",self.path)
        files = dlg.getFiles() # los hay repetidos
        self.roisShapefiles = []
        self.numberOfRoisLineEdit.setText("0")
        for file in files:
            fileBaseName = QFileInfo(file).baseName()
            findFile = False
            for roiFile in self.roisShapefiles:
                if fileBaseName == QFileInfo(roiFile).baseName():
                    findFile = True
                    break
            if not findFile:
                self.roisShapefiles.append(file)
        self.roisFilesActiveFileExtensions = dlg.getActiveFileExtensions()
        self.numberOfRoisLineEdit.setText(str(len(self.roisShapefiles)))
        return

    def selectSPSFFields(self):
        self.spsfProcessPushButton.setEnabled(False)
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_POWERLINE.lower():
            return
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        if len(self.solarParkFiles) != 1:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select one solar park shapefile")
            msgBox.exec_()
            return
        solarParkShapefile = self.solarParkFiles[0]
        ret = self.iPyProject.mmtSelectSolarParkShapefileFields(dbFileName,
                                                                solarParkShapefile)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        else:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Process completed successfully")
            msgBox.exec_()
        selectFieldsIsCompleted=ret[1]
        if selectFieldsIsCompleted == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Field selection has not been completed. You must do it before importing it")
            msgBox.exec_()
        else:
            self.spsfProcessPushButton.setEnabled(True)
        return

    def selectSPSFs(self):
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_POWERLINE.lower():
            return
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        self.spsfProcessPushButton.setEnabled(False)
        previousFiles = self.solarParkFiles[:] # copia desligada
        previousFile = None
        if len(previousFiles) == 1:
            previousFile = previousFiles[0]
        dlg = MultipleFileSelectorDialog(self.iface,
                                         self.path,
                                         MMTDefinitions.CONST_SELECT_POWER_LINES_FILES_DIALOG_TITLE,
                                         self.solarParkFilesFileTypes,
                                         self.solarParkFiles,
                                         self.solarParkFilesActiveFileExtensions)
        dlg.show() # show the dialog
        result = dlg.exec_() # Run the dialog
        self.path = dlg.getPath()
        self.settings.setValue("last_path",self.path)
        files = dlg.getFiles() # los hay repetidos
        self.solarParkFiles = []
        self.numberOfSPSFsLineEdit.setText("0")
        for file in files:
            fileBaseName = QFileInfo(file).baseName()
            findFile = False
            for pointCloudFile in self.solarParkFiles:
                if fileBaseName == QFileInfo(pointCloudFile).baseName():
                    findFile = True
                    break
            if not findFile:
                self.solarParkFiles.append(file)
        if len(self.solarParkFiles)>1:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Only one shapefile file is allowed in the current version")
            msgBox.exec_()
            self.selectSPSFs()
            return
        self.solarParkFilesActiveFileExtensions = dlg.getActiveFileExtensions()
        self.numberOfSPSFsLineEdit.setText(str(len(self.solarParkFiles)))
        if len(self.solarParkFiles)==1:
            self.spdSelectSFFieldsPushButton.setEnabled(True)
            currentFile = self.solarParkFiles[0]
            if previousFile:
                if currentFile != previousFile:
                    ret = self.iPyProject.mmtClearSolarParkShapefileFields(dbFileName)
                    if ret[0] == "False":
                        msgBox = QMessageBox(self)
                        msgBox.setIcon(QMessageBox.Information)
                        msgBox.setWindowTitle(self.windowTitle)
                        msgBox.setText("Error:\n" + ret[1])
                        msgBox.exec_()
                        return
                    self.spdSelectSFFieldsPushButton.setEnabled(False)
        if len(self.solarParkFiles)==0:
            if previousFile:
                ret = self.iPyProject.mmtClearSolarParkShapefileFields(dbFileName)
                if ret[0] == "False":
                    msgBox = QMessageBox(self)
                    msgBox.setIcon(QMessageBox.Information)
                    msgBox.setWindowTitle(self.windowTitle)
                    msgBox.setText("Error:\n" + ret[1])
                    msgBox.exec_()
                    return
            self.spdSelectSFFieldsPushButton.setEnabled(False)
        return

    def selectUpdateReferenceLayers(self):
        self.reportReferenceLayerComboBox.clear()
        self.reportReferenceLayerComboBox.addItem(MMTDefinitions.CONST_NO_COMBO_SELECT)

    def spsfProcess(self):
        if self.projectType.lower() == MMTDefinitions.CONST_PROJECT_TYPE_POWERLINE.lower():
            return
        dbFileName = self.modelManagementConnections[self.projectsComboBox.currentText()]
        if not dbFileName:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select Db file")
            msgBox.exec_()
            return
        if len(self.solarParkFiles) != 1:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Select one solar park shapefile")
            msgBox.exec_()
            return
        solarParkShapefile = self.solarParkFiles[0]
        altitudeIsMsl = True
        if self.plsfAltitudeEllipsoidRadioButton.isChecked():
            altitudeIsMsl = False
        ret = self.iPyProject.mmtSolarParkDefinition(dbFileName,
                                                     solarParkShapefile,
                                                     altitudeIsMsl)
        if ret[0] == "False":
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Error:\n"+ret[1])
            msgBox.exec_()
            return
        else:
            msgBox = QMessageBox(self)
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle(self.windowTitle)
            msgBox.setText("Process completed successfully")
            msgBox.exec_()
        # self.loadElectricPylonsLayer()
        return